#!/bin/bash
TMP_DIR=/tmp/wa-setup

date > ~/user-data-time.txt

DEBIAN_FRONTEND=noninteractive apt --assume-yes update
DEBIAN_FRONTEND=noninteractive apt --assume-yes upgrade
DEBIAN_FRONTEND=noninteractive apt --assume-yes install git

git clone https://github.com/dirkbr/wa-deployment.git ${TMP_DIR}/wa-deployment
bash ${TMP_DIR}/wa-deployment/init.sh

date >> ~/user-data-time.txt
