#!/bin/bash

date > user-data-time.txt

DEBIAN_FRONTEND=noninteractive apt --assume-yes update
DEBIAN_FRONTEND=noninteractive apt --assume-yes install git nano htop

git clone https://github.com/thecodingmachine/workadventure.git /opt/workadventure
git clone https://github.com/dirkbr/wa-deployment.git /opt/wa-deployment

cp --backup /opt/wa-deployment/.env /opt/workadventure/.env
cp --backup /opt/wa-deployment/docker-compose.yaml /opt/workadventure/docker-compose.yaml

/opt/wa-deployment/install-docker.sh

date >> user-data-time.txt
